### ISSUE TITLE
NodeError: write after end

### ISSUE THREAD

**Issue by vajahath** [vajahath/generator-ts-np#59]
Causing critical issue in v3.1.0.
Hence it is deprecated and changed the tag.

Issue details. This happens in the writing phase.
```
events.js:298
      throw er; // Unhandled 'error' event
      ^

NodeError: write after end
    at writeAfterEnd (/home/qbuser/.nvm/versions/node/v13.6.0/lib/node_modules/generator-ts-np/node_modules/readable-stream/lib/_stream_writable.js:261:12)
    at Duplexify.Writable.write (/home/qbuser/.nvm/versions/node/v13.6.0/lib/node_modules/generator-ts-np/node_modules/readable-stream/lib/_stream_writable.js:305:21)
    at DestroyableTransform.ondata (/home/qbuser/.nvm/versions/node/v13.6.0/lib/node_modules/generator-ts-np/node_modules/readable-stream/lib/_stream_readable.js:681:20)

```

**Comment by vajahath** [comment]
This issue was related to in consistent node_modules dependency tree.
Fixed by shipping the srinkwrap along with the package.

**Comment by vajahath** [comment]
wow great work vajahath
you're really good at this :clap:
